<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
=======
// Generated by CoffeeScript 1.9.3
>>>>>>> 1.9.3

/*
SkinnyMochaHalfCaffScript Compiler v1.0
Released under the MIT License
 */

(function() {


}).call(this);
