<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var fs;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var fs;
=======
// Generated by CoffeeScript 1.9.3
var fs;
>>>>>>> 1.9.3

  fs = require('fs');

  option('-o', '--output [DIR]', 'directory for compiled code');

<<<<<<< HEAD
  task('build:parser', 'rebuild the Jison parser', function(options) {
    var code, dir;
    require('jison');
    code = require('./lib/grammar').parser.generate();
    dir = options.output || 'lib';
    return fs.writeFile("" + dir + "/parser.js", code);
  });

}).call(this);
||||||| merged common ancestors
task('build:parser', 'rebuild the Jison parser', function(options) {
  var code, dir;
  require('jison');
  code = require('./lib/grammar').parser.generate();
  dir = options.output || 'lib';
  return fs.writeFile("" + dir + "/parser.js", code);
});
=======
task('build:parser', 'rebuild the Jison parser', function(options) {
  var code, dir;
  require('jison');
  code = require('./lib/grammar').parser.generate();
  dir = options.output || 'lib';
  return fs.writeFile(dir + "/parser.js", code);
});
>>>>>>> 1.9.3
