// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  $('body').click(function(e) {
    return $('.box').fadeIn('fast').addClass('.active');
  }).css('background', 'white');

}).call(this);
