<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  $('body').click(function(e) {
    return $('.box').fadeIn('fast').addClass('.active');
  }).css('background', 'white');

}).call(this);
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
$('body').click(function(e) {
  return $('.box').fadeIn('fast').addClass('.active');
}).css('background', 'white');
=======
// Generated by CoffeeScript 1.9.3
$('body').click(function(e) {
  return $('.box').fadeIn('fast').addClass('.active');
}).css('background', 'white');
>>>>>>> 1.9.3
