// Generated by CoffeeScript 1.7.0-reflective.22
(function() {
  $('body').click(function(e) {
    return $('.box').fadeIn('fast').addClass('.active');
  }).css('background', 'white');

}).call(this);
