<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var cholesterol, healthy;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var cholesterol, healthy;
=======
// Generated by CoffeeScript 1.9.3
var cholesterol, healthy;
>>>>>>> 1.9.3

  cholesterol = 127;

  healthy = (200 > cholesterol && cholesterol > 60);

}).call(this);
