// Generated by CoffeeScript 1.7.0-reflective.22
(function() {
  var date, mood;

  if (singing) {
    mood = greatlyImproved;
  }

  if (happy && knowsIt) {
    clapsHands();
    chaChaCha();
  } else {
    showIt();
  }

  date = friday ? sue : jill;

}).call(this);
