<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var date, mood;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var date, mood;
=======
// Generated by CoffeeScript 1.9.3
var date, mood;
>>>>>>> 1.9.3

  if (singing) {
    mood = greatlyImproved;
  }

  if (happy && knowsIt) {
    clapsHands();
    chaChaCha();
  } else {
    showIt();
  }

  date = friday ? sue : jill;

}).call(this);
