<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var Person, tim;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var Person, tim;
=======
// Generated by CoffeeScript 1.9.3
var Person, tim;
>>>>>>> 1.9.3

  Person = (function() {
    function Person(options) {
      this.name = options.name, this.age = options.age, this.height = options.height;
    }

    return Person;

  })();

  tim = new Person({
    age: 4
  });

}).call(this);
