<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var fill;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var fill;
=======
// Generated by CoffeeScript 1.9.3
var fill;
>>>>>>> 1.9.3

  fill = function(container, liquid) {
    if (liquid == null) {
      liquid = "coffee";
    }
    return "Filling the " + container + " with " + liquid + "...";
  };

}).call(this);
