<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var filename, _fn, _i, _len;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var filename, _fn, _i, _len;
=======
// Generated by CoffeeScript 1.9.3
var filename, fn, i, len;
>>>>>>> 1.9.3

<<<<<<< HEAD
  _fn = function(filename) {
    return fs.readFile(filename, function(err, contents) {
      return compile(filename, contents.toString());
    });
  };
  for (_i = 0, _len = list.length; _i < _len; _i++) {
    filename = list[_i];
    _fn(filename);
  }

}).call(this);
||||||| merged common ancestors
_fn = function(filename) {
  return fs.readFile(filename, function(err, contents) {
    return compile(filename, contents.toString());
  });
};
for (_i = 0, _len = list.length; _i < _len; _i++) {
  filename = list[_i];
  _fn(filename);
}
=======
fn = function(filename) {
  return fs.readFile(filename, function(err, contents) {
    return compile(filename, contents.toString());
  });
};
for (i = 0, len = list.length; i < len; i++) {
  filename = list[i];
  fn(filename);
}
>>>>>>> 1.9.3
