<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var hi;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var hi;
=======
// Generated by CoffeeScript 1.9.3
var hi;
>>>>>>> 1.9.3

  hi = function() {
  return [document.title, "Hello JavaScript"].join(": ");
};

}).call(this);
