<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var footprints, solipsism, speed;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var footprints, solipsism, speed;
=======
// Generated by CoffeeScript 1.9.3
var footprints, solipsism, speed;
>>>>>>> 1.9.3

  if ((typeof mind !== "undefined" && mind !== null) && (typeof world === "undefined" || world === null)) {
    solipsism = true;
  }

  speed = 0;

  if (speed == null) {
    speed = 15;
  }

  footprints = typeof yeti !== "undefined" && yeti !== null ? yeti : "bear";

}).call(this);
