// Generated by CoffeeScript 1.7.0-reflective.22
(function() {
  var footprints, solipsism, speed;

  if ((typeof mind !== "undefined" && mind !== null) && (typeof world === "undefined" || world === null)) {
    solipsism = true;
  }

  speed = 0;

  if (speed == null) {
    speed = 15;
  }

  footprints = typeof yeti !== "undefined" && yeti !== null ? yeti : "bear";

}).call(this);
