<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var first, last, text, _ref;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var first, last, text, _ref;
=======
// Generated by CoffeeScript 1.9.3
var first, last, ref, text;
>>>>>>> 1.9.3

  text = "Every literary critic believes he will outwit history and have the last word";

<<<<<<< HEAD
  _ref = text.split(" "), first = _ref[0], last = _ref[_ref.length - 1];

}).call(this);
||||||| merged common ancestors
_ref = text.split(" "), first = _ref[0], last = _ref[_ref.length - 1];
=======
ref = text.split(" "), first = ref[0], last = ref[ref.length - 1];
>>>>>>> 1.9.3
