// Generated by Reflective CoffeeScript 1.10.0-reflective.111
var first, last, ref, text;

text = "Every literary critic believes he will outwit history and have the last word";

ref = text.split(" "), first = ref[0], last = ref[ref.length - 1];
