// Generated by Reflective CoffeeScript 1.10.0-reflective.111
var globals, name;

globals = ((function() {
  var results;
  results = [];
  for (name in window) {
    results.push(name);
  }
  return results;
})()).slice(0, 10);
