// Generated by CoffeeScript 1.7.0-reflective.22
(function() {
  var error;

  alert((function() {
    try {
      return nonexistent / void 0;
    } catch (_error) {
      error = _error;
      return "And the error is ... " + error;
    }
  })());

}).call(this);
