<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var error;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var error;
=======
// Generated by CoffeeScript 1.9.3
var error;
>>>>>>> 1.9.3

  alert((function() {
    try {
      return nonexistent / void 0;
    } catch (_error) {
      error = _error;
      return "And the error is ... " + error;
    }
  })());

}).call(this);
