<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var one, six, three, two;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var one, six, three, two;
=======
// Generated by CoffeeScript 1.9.3
var one, six, three, two;
>>>>>>> 1.9.3

  six = (one = 1) + (two = 2) + (three = 3);

}).call(this);
