<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var globals, name;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var globals, name;
=======
// Generated by CoffeeScript 1.9.3
var globals, name;
>>>>>>> 1.9.3

<<<<<<< HEAD
  globals = ((function() {
    var _results;
    _results = [];
    for (name in window) {
      _results.push(name);
    }
    return _results;
  })()).slice(0, 10);

}).call(this);
||||||| merged common ancestors
globals = ((function() {
  var _results;
  _results = [];
  for (name in window) {
    _results.push(name);
  }
  return _results;
})()).slice(0, 10);
=======
globals = ((function() {
  var results;
  results = [];
  for (name in window) {
    results.push(name);
  }
  return results;
})()).slice(0, 10);
>>>>>>> 1.9.3
