<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var Account;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var Account;
=======
// Generated by CoffeeScript 1.9.3
var Account;
>>>>>>> 1.9.3

<<<<<<< HEAD
  Account = function(customer, cart) {
    this.customer = customer;
    this.cart = cart;
    return $('.shopping_cart').bind('click', (function(_this) {
      return function(event) {
        return _this.customer.purchase(_this.cart);
      };
    })(this));
  };

}).call(this);
||||||| merged common ancestors
Account = function(customer, cart) {
  this.customer = customer;
  this.cart = cart;
  return $('.shopping_cart').bind('click', (function(_this) {
    return function(event) {
      return _this.customer.purchase(_this.cart);
    };
  })(this));
};
=======
Account = function(customer, cart) {
  this.customer = customer;
  this.cart = cart;
  return $('.shopping_cart').on('click', (function(_this) {
    return function(event) {
      return _this.customer.purchase(_this.cart);
    };
  })(this));
};
>>>>>>> 1.9.3
