<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var cube, square;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var cube, square;
=======
// Generated by CoffeeScript 1.9.3
var cube, square;
>>>>>>> 1.9.3

  square = function(x) {
    return x * x;
  };

  cube = function(x) {
    return square(x) * x;
  };

}).call(this);
