<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var OPERATOR;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var OPERATOR;
=======
// Generated by CoffeeScript 1.9.3
var OPERATOR;
>>>>>>> 1.9.3

  OPERATOR = /^(?:[-=]>|[-+*\/%<>&|^!?=]=|>>>=?|([-+:])\1|([&|<>])\2=?|\?\.|\.{2,3})/;

}).call(this);
