<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var html;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var html;
=======
// Generated by CoffeeScript 1.9.3
var html;
>>>>>>> 1.9.3

  html = "<strong>\n  cup of coffeescript\n</strong>";

}).call(this);
