// Generated by CoffeeScript 1.8.0-reflective.23
(function() {
  var author, quote, sentence;

  author = "Wittgenstein";

  quote = "A picture is a fact. -- " + author;

  sentence = "" + (22 / 7) + " is a decent approximation of π";

}).call(this);
