// Generated by Reflective CoffeeScript 1.10.0-reflective.111
var author, quote, sentence;

author = "Wittgenstein";

quote = "A picture is a fact. -- " + author;

sentence = (22 / 7) + " is a decent approximation of π";
