<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var city, forecast, temp, weatherReport, _ref;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var city, forecast, temp, weatherReport, _ref;
=======
// Generated by CoffeeScript 1.9.3
var city, forecast, ref, temp, weatherReport;
>>>>>>> 1.9.3

  weatherReport = function(location) {
    return [location, 72, "Mostly Sunny"];
  };

<<<<<<< HEAD
  _ref = weatherReport("Berkeley, CA"), city = _ref[0], temp = _ref[1], forecast = _ref[2];

}).call(this);
||||||| merged common ancestors
_ref = weatherReport("Berkeley, CA"), city = _ref[0], temp = _ref[1], forecast = _ref[2];
=======
ref = weatherReport("Berkeley, CA"), city = ref[0], temp = ref[1], forecast = ref[2];
>>>>>>> 1.9.3
