<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var age, ages, child, yearsOld;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var age, ages, child, yearsOld;
=======
// Generated by CoffeeScript 1.9.3
var age, ages, child, yearsOld;
>>>>>>> 1.9.3

  yearsOld = {
    max: 10,
    ida: 9,
    tim: 11
  };

<<<<<<< HEAD
  ages = (function() {
    var _results;
    _results = [];
    for (child in yearsOld) {
      age = yearsOld[child];
      _results.push("" + child + " is " + age);
    }
    return _results;
  })();

}).call(this);
||||||| merged common ancestors
ages = (function() {
  var _results;
  _results = [];
  for (child in yearsOld) {
    age = yearsOld[child];
    _results.push("" + child + " is " + age);
  }
  return _results;
})();
=======
ages = (function() {
  var results;
  results = [];
  for (child in yearsOld) {
    age = yearsOld[child];
    results.push(child + " is " + age);
  }
  return results;
})();
>>>>>>> 1.9.3
