<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  $('.account').attr({
    "class": 'active'
  });
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
$('.account').attr({
  "class": 'active'
});
=======
// Generated by CoffeeScript 1.9.3
$('.account').attr({
  "class": 'active'
});
>>>>>>> 1.9.3

  log(object["class"]);

}).call(this);
