<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var bitlist, kids, singers, song;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var bitlist, kids, singers, song;
=======
// Generated by CoffeeScript 1.9.3
var bitlist, kids, singers, song;
>>>>>>> 1.9.3

  song = ["do", "re", "mi", "fa", "so"];

  singers = {
    Jagger: "Rock",
    Elvis: "Roll"
  };

  bitlist = [1, 0, 1, 0, 0, 1, 1, 1, 0];

  kids = {
    brother: {
      name: "Max",
      age: 11
    },
    sister: {
      name: "Ida",
      age: 9
    }
  };

}).call(this);
