<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var city, futurists, name, street, _ref, _ref1;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var city, futurists, name, street, _ref, _ref1;
=======
// Generated by CoffeeScript 1.9.3
var city, futurists, name, ref, ref1, street;
>>>>>>> 1.9.3

  futurists = {
    sculptor: "Umberto Boccioni",
    painter: "Vladimir Burliuk",
    poet: {
      name: "F.T. Marinetti",
      address: ["Via Roma 42R", "Bellagio, Italy 22021"]
    }
  };

<<<<<<< HEAD
  _ref = futurists.poet, name = _ref.name, (_ref1 = _ref.address, street = _ref1[0], city = _ref1[1]);

}).call(this);
||||||| merged common ancestors
_ref = futurists.poet, name = _ref.name, (_ref1 = _ref.address, street = _ref1[0], city = _ref1[1]);
=======
ref = futurists.poet, name = ref.name, (ref1 = ref.address, street = ref1[0], city = ref1[1]);
>>>>>>> 1.9.3
