// Generated by CoffeeScript 1.7.0-reflective.22
(function() {
  var theBait, theSwitch, _ref;

  theBait = 1000;

  theSwitch = 0;

  _ref = [theSwitch, theBait], theBait = _ref[0], theSwitch = _ref[1];

}).call(this);
