<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var theBait, theSwitch, _ref;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var theBait, theSwitch, _ref;
=======
// Generated by CoffeeScript 1.9.3
var ref, theBait, theSwitch;
>>>>>>> 1.9.3

  theBait = 1000;

  theSwitch = 0;

<<<<<<< HEAD
  _ref = [theSwitch, theBait], theBait = _ref[0], theSwitch = _ref[1];

}).call(this);
||||||| merged common ancestors
_ref = [theSwitch, theBait], theBait = _ref[0], theSwitch = _ref[1];
=======
ref = [theSwitch, theBait], theBait = ref[0], theSwitch = ref[1];
>>>>>>> 1.9.3
