<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var close, contents, open, tag, _i, _ref,
    __slice = [].slice;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var close, contents, open, tag, _i, _ref,
  __slice = [].slice;
=======
// Generated by CoffeeScript 1.9.3
var close, contents, i, open, ref, tag,
  slice = [].slice;
>>>>>>> 1.9.3

  tag = "<impossible>";

<<<<<<< HEAD
  _ref = tag.split(""), open = _ref[0], contents = 3 <= _ref.length ? __slice.call(_ref, 1, _i = _ref.length - 1) : (_i = 1, []), close = _ref[_i++];

}).call(this);
||||||| merged common ancestors
_ref = tag.split(""), open = _ref[0], contents = 3 <= _ref.length ? __slice.call(_ref, 1, _i = _ref.length - 1) : (_i = 1, []), close = _ref[_i++];
=======
ref = tag.split(""), open = ref[0], contents = 3 <= ref.length ? slice.call(ref, 1, i = ref.length - 1) : (i = 1, []), close = ref[i++];
>>>>>>> 1.9.3
