<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  String.prototype.dasherize = function() {
    return this.replace(/_/g, "-");
  };

}).call(this);
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
String.prototype.dasherize = function() {
  return this.replace(/_/g, "-");
};
=======
// Generated by CoffeeScript 1.9.3
String.prototype.dasherize = function() {
  return this.replace(/_/g, "-");
};
>>>>>>> 1.9.3
