<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var countdown, num;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var countdown, num;
=======
// Generated by CoffeeScript 1.9.3
var countdown, num;
>>>>>>> 1.9.3

<<<<<<< HEAD
  countdown = (function() {
    var _i, _results;
    _results = [];
    for (num = _i = 10; _i >= 1; num = --_i) {
      _results.push(num);
    }
    return _results;
  })();

}).call(this);
||||||| merged common ancestors
countdown = (function() {
  var _i, _results;
  _results = [];
  for (num = _i = 10; _i >= 1; num = --_i) {
    _results.push(num);
  }
  return _results;
})();
=======
countdown = (function() {
  var i, results;
  results = [];
  for (num = i = 10; i >= 1; num = --i) {
    results.push(num);
  }
  return results;
})();
>>>>>>> 1.9.3
