// Generated by CoffeeScript 1.7.0-reflective.22
(function() {
  var changeNumbers, inner, outer;

  outer = 1;

  changeNumbers = function() {
    var inner;
    inner = -1;
    return outer = 10;
  };

  inner = changeNumbers();

}).call(this);
