<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var changeNumbers, inner, outer;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var changeNumbers, inner, outer;
=======
// Generated by CoffeeScript 1.9.3
var changeNumbers, inner, outer;
>>>>>>> 1.9.3

  outer = 1;

  changeNumbers = function() {
    var inner;
    inner = -1;
    return outer = 10;
  };

  inner = changeNumbers();

}).call(this);
