<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var copy, end, middle, numbers, start;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var copy, end, middle, numbers, start;
=======
// Generated by CoffeeScript 1.9.3
var copy, end, middle, numbers, start;
>>>>>>> 1.9.3

  numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9];

  start = numbers.slice(0, 3);

  middle = numbers.slice(3, -2);

  end = numbers.slice(-2);

  copy = numbers.slice(0);

}).call(this);
