// Generated by CoffeeScript 1.7.0-reflective.22
(function() {
  var zip, _ref;

  zip = typeof lottery.drawWinner === "function" ? (_ref = lottery.drawWinner().address) != null ? _ref.zipcode : void 0 : void 0;

}).call(this);
