<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var zip, _ref;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var zip, _ref;
=======
// Generated by CoffeeScript 1.9.3
var ref, zip;
>>>>>>> 1.9.3

<<<<<<< HEAD
  zip = typeof lottery.drawWinner === "function" ? (_ref = lottery.drawWinner().address) != null ? _ref.zipcode : void 0 : void 0;

}).call(this);
||||||| merged common ancestors
zip = typeof lottery.drawWinner === "function" ? (_ref = lottery.drawWinner().address) != null ? _ref.zipcode : void 0 : void 0;
=======
zip = typeof lottery.drawWinner === "function" ? (ref = lottery.drawWinner().address) != null ? ref.zipcode : void 0 : void 0;
>>>>>>> 1.9.3
