<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var awardMedals, contenders, gold, rest, silver,
    __slice = [].slice;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var awardMedals, contenders, gold, rest, silver,
  __slice = [].slice;
=======
// Generated by CoffeeScript 1.9.3
var awardMedals, contenders, gold, rest, silver,
  slice = [].slice;
>>>>>>> 1.9.3

  gold = silver = rest = "unknown";

<<<<<<< HEAD
  awardMedals = function() {
    var first, others, second;
    first = arguments[0], second = arguments[1], others = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
    gold = first;
    silver = second;
    return rest = others;
  };
||||||| merged common ancestors
awardMedals = function() {
  var first, others, second;
  first = arguments[0], second = arguments[1], others = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
  gold = first;
  silver = second;
  return rest = others;
};
=======
awardMedals = function() {
  var first, others, second;
  first = arguments[0], second = arguments[1], others = 3 <= arguments.length ? slice.call(arguments, 2) : [];
  gold = first;
  silver = second;
  return rest = others;
};
>>>>>>> 1.9.3

  contenders = ["Michael Phelps", "Liu Xiang", "Yao Ming", "Allyson Felix", "Shawn Johnson", "Roman Sebrle", "Guo Jingjing", "Tyson Gay", "Asafa Powell", "Usain Bolt"];

  awardMedals.apply(null, contenders);

  alert("Gold: " + gold);

  alert("Silver: " + silver);

  alert("The Field: " + rest);

}).call(this);
