<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var numbers, _ref;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var numbers, _ref;
=======
// Generated by CoffeeScript 1.9.3
var numbers, ref;
>>>>>>> 1.9.3

  numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];

<<<<<<< HEAD
  [].splice.apply(numbers, [3, 4].concat(_ref = [-3, -4, -5, -6])), _ref;

}).call(this);
||||||| merged common ancestors
[].splice.apply(numbers, [3, 4].concat(_ref = [-3, -4, -5, -6])), _ref;
=======
[].splice.apply(numbers, [3, 4].concat(ref = [-3, -4, -5, -6])), ref;
>>>>>>> 1.9.3
