<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var mobyDick;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var mobyDick;
=======
// Generated by CoffeeScript 1.9.3
var mobyDick;
>>>>>>> 1.9.3

  mobyDick = "Call me Ishmael. Some years ago -- never mind how long precisely -- having little or no money in my purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world...";

}).call(this);
