<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var grade, score;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var grade, score;
=======
// Generated by CoffeeScript 1.9.3
var grade, score;
>>>>>>> 1.9.3

  score = 76;

  grade = (function() {
    switch (false) {
      case !(score < 60):
        return 'F';
      case !(score < 70):
        return 'D';
      case !(score < 80):
        return 'C';
      case !(score < 90):
        return 'B';
      default:
        return 'A';
    }
  })();

}).call(this);
