// Generated by CoffeeScript 1.8.0-reflective.23
(function() {
  var error;

  try {
    allHellBreaksLoose();
    catsAndDogsLivingTogether();
  } catch (_error) {
    error = _error;
    print(error);
  } finally {
    cleanUp();
  }

}).call(this);
