// Generated by CoffeeScript 1.10.0-reflective.32
var error, error1;

try {
  allHellBreaksLoose();
  catsAndDogsLivingTogether();
} catch (error1) {
  error = error1;
  print(error);
} finally {
  cleanUp();
}
