<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0-reflective.24
(function() {
  var lyrics, num;
||||||| merged common ancestors
// Generated by CoffeeScript 1.8.0
var lyrics, num;
=======
// Generated by CoffeeScript 1.9.3
var lyrics, num;
>>>>>>> 1.9.3

  if (this.studyingEconomics) {
    while (supply > demand) {
      buy();
    }
    while (!(supply > demand)) {
      sell();
    }
  }

  num = 6;

<<<<<<< HEAD
  lyrics = (function() {
    var _results;
    _results = [];
    while (num -= 1) {
      _results.push("" + num + " little monkeys, jumping on the bed. One fell out and bumped his head.");
    }
    return _results;
  })();

}).call(this);
||||||| merged common ancestors
lyrics = (function() {
  var _results;
  _results = [];
  while (num -= 1) {
    _results.push("" + num + " little monkeys, jumping on the bed. One fell out and bumped his head.");
  }
  return _results;
})();
=======
lyrics = (function() {
  var results;
  results = [];
  while (num -= 1) {
    results.push(num + " little monkeys, jumping on the bed. One fell out and bumped his head.");
  }
  return results;
})();
>>>>>>> 1.9.3
